name: Print Date

on:
    push:
        branches: [master]

jobs:
    build-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Print date
              run: |
                date
    
    build-windows:
        runs-on: windows-latest
        steps:
            - name: Print date
              run: |
                date

    dependent-job:
        runs-on: ubuntu-latest
        needs: [build-ubuntu, build-windows]
        steps:
            - name: Meow
              run: |
                man date

